canonical/kubeflow-tensorboards-operator

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
.gitignore
CODEOWNERS
config.yaml
metadata.yaml
requirements.txt
src/charm.py
test-requirements.txt
tests/test_operator.py
tox.ini

Initial operator implementation

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboards-web-app/metadata.yaml

chore: Bump image versions

---

charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_info.py
charms/tensorboard-controller/metadata.yaml
charms/tensorboard-controller/src/charm.py
charms/tensorboard-controller/tests/unit/test_charm.py
tests/integration/test_charms.py

Backport gateway relation changes

---

README.md

documentation update on Usage and examples included

Updated the Tensorboards Operator Readme

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
charms/tensorboard-controller/metadata.yaml
charms/tensorboard-controller/test-requirements.txt
charms/tensorboards-web-app/metadata.yaml
charms/tensorboards-web-app/test-requirements.txt

Bumps tensorboards images to kf 1.6.1, and fixes bugs with the publish CI action

feat: bump track 1.6 to 1.6.1, fix CI

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboard-controller/test-requirements.txt
charms/tensorboards-web-app/metadata.yaml
charms/tensorboards-web-app/test-requirements.txt

git-xargs programmatic pull request

Update to 1.6.1

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboards-web-app/metadata.yaml

bumped controller and web-app images from 1.6.1 to 1.7.0-rc.0

1.7 upgrades

---

.github/workflows/integrate.yaml

remove configure kubectl done automatically

fix: update integrate.yaml

---

.github/workflows/integrate.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml

* start using templates instead of individual CI files
* added consistency to the secrets by using inheritance

use templates in integrate

---

.github/workflows/integrate.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml

added reusable templates for CI

[backport] use templates in integrate (#64)

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboards-web-app/metadata.yaml

feat: version bump 1.7.0-rc.1->1.7.0

feat: version bump 1.7.0-rc.1->1.7.0

---

charms/tensorboard-controller/tox.ini
charms/tensorboards-web-app/tox.ini
tox.ini

Updates tox.ini's `update-requirements` as described in https://github.com/canonical/argo-operators/pull/100

update tox.ini's update-requirements

---

.github/workflows/integrate.yaml
charms/tensorboard-controller/requirements-integration.in
charms/tensorboard-controller/requirements-integration.txt
charms/tensorboards-web-app/requirements-integration.in
charms/tensorboards-web-app/requirements-integration.txt
requirements-integration.in
requirements-integration.txt

ci: update juju to 3.1 and microk8s to 1.25

ci: update juju to 3.1 and microk8s to 1.25

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboards-web-app/metadata.yaml

Fixed image based on https://github.com/kubeflow/manifests/pull/2567/files

Update image and manifests for v1.8

---

charms/tensorboard-controller/requirements-integration.txt
charms/tensorboard-controller/requirements-unit.txt
charms/tensorboard-controller/requirements.txt
charms/tensorboards-web-app/requirements-integration.txt
charms/tensorboards-web-app/requirements-unit.txt
charms/tensorboards-web-app/requirements.txt

Part of canonical/bundle-kubeflow#868

build: bump ops to latest possible version

---

charms/tensorboard-controller/requirements-unit.txt
charms/tensorboard-controller/requirements.txt
charms/tensorboards-web-app/requirements-unit.txt
charms/tensorboards-web-app/requirements.txt

Part of canonical/bundle-kubeflow#883

build: bump jinja2 3.1.x -> 3.1.4

---

charms/tensorboard-controller/requirements-unit.txt
charms/tensorboard-controller/requirements.txt
charms/tensorboards-web-app/requirements-unit.txt
charms/tensorboards-web-app/requirements.txt

Part of canonical/bundle-kubeflow#883

build: bump jinja2 3.1.x -> 3.1.4 (#125)

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboards-web-app/metadata.yaml
charms/tensorboards-web-app/src/charm.py

Fixes #135
(will forward port to main)

chore: integrate rocks for 1.9.0

---

charms/tensorboard-controller/lib/charms/loki_k8s/v1/loki_push_api.py
charms/tensorboard-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/tensorboards-web-app/lib/charms/loki_k8s/v1/loki_push_api.py
charms/tensorboards-web-app/lib/charms/observability_libs/v1/kubernetes_service_patch.py

* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184

chore: bump libraries

---

charms/tensorboard-controller/metadata.yaml
charms/tensorboards-web-app/metadata.yaml

Close https://warthogs.atlassian.net/browse/KF-6962
Close https://warthogs.atlassian.net/browse/KF-6963

chore: integrate 1.10.0-rc.0 rocks

---

charms/tensorboard-controller/terraform/versions.tf
charms/tensorboards-web-app/terraform/versions.tf

Updating juju provider requirement to >=0.14.0

[KF-7255] Update Juju provider

---

charms/tensorboard-controller/terraform/variables.tf
charms/tensorboard-controller/terraform/versions.tf
charms/tensorboards-web-app/terraform/variables.tf
charms/tensorboards-web-app/terraform/versions.tf

Cutting new release for branch track/1.10

[KF-7254] Release 1.10

---

charms/tensorboard-controller/terraform/variables.tf
charms/tensorboards-web-app/terraform/variables.tf

[KF-7268] chore: pin channel to latest/edge

---

.github/workflows/tiobe_scan.yml
charms/tensorboard-controller/tox.ini
charms/tensorboards-web-app/tox.ini

Updating with TIOBE scan, including:
* reformatting tox.ini file to be machine-generated and handled
* coverage.xml generation when running unit tests 
* creating tiobe_scan.yaml file

[KF-7281] Enabling TIOBE scan

---

charms/tensorboard-controller/tests/integration/utils.py
charms/tensorboards-web-app/tests/integration/test_charm.py
tests/integration/test_charms.py

Pin charms-dependencies according to 1.10/stable bundle.
Close https://warthogs.atlassian.net/browse/KF-7233

chore(tests): Pin charms-dependencies

---

charms/tensorboard-controller/config.yaml
charms/tensorboard-controller/src/charm.py

Part of https://github.com/canonical/bundle-kubeflow/issues/1262
Once https://github.com/canonical/tensorflow-rock/pull/3 is merged, a follow-up PR will be opened to integrate the rock.

feat: add config option for tensorboard image

---

charms/tensorboard-controller/config.yaml
charms/tensorboard-controller/src/charm.py

chore(backport): integrate tensorflow rock
