canonical/kubeflow-tensorboards-operator

charms/tensorboards-web-app/src/charm.py
fixes error where non-string input will cause an exception when instantiating the `status`
=> fix: force CheckFailed msg arg to string

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml
This PR addresses GH-425 where a PVC is created per operator, adding the `min-juju-version: 2.9.0` element to prevent that PVC creation.
=> Add min-juju-version element to prevent excess PVC creation

.github/workflows/integrate.yaml, .gitignore, charms/tensorboard-controller/files/crds.yaml, charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_name.py, charms/tensorboard-controller/metadata.yaml, charms/tensorboard-controller/src/charm.py, charms/tensorboard-controller/tests/unit/test_charm.py, charms/tensorboards-web-app/metadata.yaml, tests/integration/test_charms.py
This PR upgrades tensorboard-controller and tensorboards-web-app to v1.6.
It updates manifest files and podspec to match latest release and points to the new images in `metadata.yaml`.
Starting from this release, istio gateway name is required as an environment variable in the podspec. `istio-pilot:gateway` relation was added to tensorboard-controller in order to ensure the pods get recreated when the gateway name is changed. Tests have been updated to cover these changes.
Both upgraded charms were deployed successfully on microk8s 1.21 and 1.22 and tested in a full bundle on 1.21.
In order to test these charms:
1. Deploy a bundle. An additional relation will be required:
`juju relate istio-pilot:gateway tensorboard-controller:gateway`
3. Connect to the dashboard.
4. Add a jupyter …
=> Upgrade to v1.6

.github/workflows/integrate.yaml
This PR updates microk8s version in CI from 1.21 to 1.22.
=> Update CI to test on microk8s 1.22

charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_name.py
The check-lib job is failing due to no `LIBID` in gateway library's metadata. Since this library is now published and the field is present, this PR updates it.
=> Fetch gateway lib from charmcraft

charms/tensorboard-controller/tests/unit/test_charm.py, charms/tensorboards-web-app/src/charm.py, charms/tensorboards-web-app/tests/test_operator.py
When we use `juju upgrade-charm`, a new non-leader unit gets created, then the old still-leader one gets removed, resulting in the new unit being elected as the leader.
When the `leader_elected` event is not observed, the charm is not aware of having a leader now, so it remains stuck with message 'Waiting for leadership'.
This PR adds a fix to observe this event in tensorboards-web-app.
=> Observe leader-elected event

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml
Version bump to 1.6.0 release image
NOTE: this PR depends on the latest image tag specified in [kubeflow/manifests](https://github.com/kubeflow/manifests/blob/v1.6-branch/apps/admission-webhook/upstream
=> chore: oci image version bump 1.6.0-rc.2 -> 1.6.0

charms/tensorboards-web-app/metadata.yaml
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
=> feat: localize SDI schemas

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml, charms/tensorboards-web-app/src/charm.py
- bump tensorboard-controller image to 1.7.0-rc.1
- bump tensorboards-web-app image to 1.7.0-rc.1
- upgrade tensorboards-web-app roles in podspec to 1.7.0-rc.1
=> Upgrade images and web-app manifests 1.7.0-rc.1

charms/tensorboards-web-app/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py, charms/tensorboards-web-app/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_sidebar.py, charms/tensorboards-web-app/metadata.yaml, charms/tensorboards-web-app/src/charm.py
Adds the sidebar relation for kubeflow-dashboard, plus the library to manage it.  This allows this charm to request a link in the kubeflow dashboard's sidebar.
=> feat: add kubeflow-dashboard sidebar relation to web-app

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml
Update `tensorboard-controller` and `tensorboards-web-app` images version to `v1.8.0-rc.0` in preparation for the 1.8 release
Based on kubeflow/manifests repo tag `v1.8.0-rc.0`.
No changes were observed for the manifests and CRDs.
=> feat: bump tensorboards charms images to 1.8.0-rc.0

charms/tensorboards-web-app/src/charm.py, charms/tensorboards-web-app/tests/integration/test_charm.py, tests/integration/test_charms.py
Pins dependencies in the integration tests to their corresponding channels for this release.
Ref: https://github.com/canonical/bundle-kubeflow/issues/866
=> pin integration test dependencies, refactor constants in tests for `track/1.8`

charms/tensorboards-web-app/src/charm.py
Related to: https://github.com/canonical/kubeflow-dashboard-operator/issues/190
[Some of the links in the configmap ](https://github.com/kubeflow/kubeflow/blob/master/components/centraldashboard/manifests/base/configmap.yaml#L7)changed upstream. This PR resolves the changes related to this charm.
=> Update dashboard link

charms/tensorboards-web-app/lib/charms/loki_k8s/v1/loki_push_api.py, charms/tensorboards-web-app/metadata.yaml, charms/tensorboards-web-app/requirements-integration.in, charms/tensorboards-web-app/requirements-integration.txt, charms/tensorboards-web-app/requirements-unit.txt, charms/tensorboards-web-app/requirements.in, charms/tensorboards-web-app/requirements.txt, charms/tensorboards-web-app/src/charm.py, charms/tensorboards-web-app/tests/integration/test_charm.py, charms/tensorboards-web-app/tests/unit/test_operator.py
Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #111
How I tested it:
```bash
$ tox -e integration -- --keep-models --model kubeflow
$ juju switch test-charm-zk9n
u1-k8s:admin/test-charm-kee3 -> u1-k8s:admin/test-charm-zk9n
$ juju consume u1-k8s:cos.loki-logging 
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate grafana-agent-k8s loki-logging
$ kubectl get services -n test-charm-zk9n | grep tensorboards-web-app
tensorboards-web-app-endpoints   ClusterIP      None             <none>        <none>                                  7m23s
tensorboards-web-app             ClusterIP      10.152.183.233   <none>        5000/TCP …
```
=> Add logging relation to tensorboards-web-app

charms/tensorboard-controller/lib/charms/loki_k8s/v1/loki_push_api.py, charms/tensorboard-controller/metadata.yaml, charms/tensorboard-controller/requirements-integration.in, charms/tensorboard-controller/requirements-integration.txt, charms/tensorboard-controller/requirements-unit.txt, charms/tensorboard-controller/requirements.in, charms/tensorboard-controller/requirements.txt, charms/tensorboard-controller/src/charm.py, charms/tensorboard-controller/tests/integration/test_charm.py, charms/tensorboard-controller/tests/unit/test_operator.py
Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #110
How I tested it:
```bash
$ tox -e integration -- --keep-models
$ juju switch test-charm-98bl
$ charmcraft pack  # since there is test removing charm
Created 'tensorboard-controller_ubuntu-20.04-amd64.charm'.
Charms packed:
tensorboard-controller_ubuntu-20.04-amd64.charm 
$ juju deploy ./tensorboard-controller_ubuntu-20.04-amd64.charm --resource tensorboard-controller-image=kubeflownotebookswg/tensorboard-controller:v1.9.0-rc.0
Located local charm "tensorboard-controller", revision 0
Deploying "tensorboard-controller" from local charm "tensorboard-controller", revision 0 on ubuntu@20.04/stable
$ juju consume …
```
=> Add logging relation to tensorboards-controller

charms/tensorboards-web-app/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
part of fixing https://github.com/canonical/kubeflow-dashboard-operator/issues/213
bumps the `KubeflowDashboardLinks` lib to Patch 3, lib was updated in https://github.com/canonical/kubeflow-dashboard-operator/pull/219
=> chore: bump dashboard links lib

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml, charms/tensorboards-web-app/src/charm.py
=> forward-port(chore): integrate rocks for 1.9.0 from #137

.github/workflows/integrate.yaml, .gitignore, charms/tensorboard-controller/terraform/README.md, charms/tensorboard-controller/terraform/main.tf, charms/tensorboard-controller/terraform/outputs.tf, charms/tensorboard-controller/terraform/variables.tf, charms/tensorboard-controller/terraform/versions.tf, charms/tensorboard-controller/tox.ini, charms/tensorboards-web-app/terraform/README.md, charms/tensorboards-web-app/terraform/main.tf, charms/tensorboards-web-app/terraform/outputs.tf, charms/tensorboards-web-app/terraform/variables.tf, charms/tensorboards-web-app/terraform/versions.tf, charms/tensorboards-web-app/tox.ini
backports #142 to `track/1.9`
ref #140 and #141
=> (backport) feat: add terraform modules for tensorboard controller and web-app charms

charms/tensorboard-controller/requirements-fmt.txt, charms/tensorboard-controller/requirements-integration.txt, charms/tensorboard-controller/requirements-lint.txt, charms/tensorboard-controller/requirements-unit.txt, charms/tensorboard-controller/requirements.txt, charms/tensorboard-controller/tox.ini, charms/tensorboards-web-app/requirements-fmt.txt, charms/tensorboards-web-app/requirements-integration.txt, charms/tensorboards-web-app/requirements-lint.txt, charms/tensorboards-web-app/requirements-unit.txt, charms/tensorboards-web-app/requirements.txt, charms/tensorboards-web-app/tox.ini, requirements-fmt.txt, requirements-integration.txt, requirements-lint.txt, tox.ini
* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
Ref canonical/bundle-kubeflow#1177
=> chore: update python dependencies + pin pip

.github/workflows/integrate.yaml, .github/workflows/publish.yaml, charms/tensorboard-controller/LICENSE, charms/tensorboard-controller/charmcraft.yaml, charms/tensorboards-web-app/LICENSE, charms/tensorboards-web-app/charmcraft.yaml
In order to be able to use the data-platform-workflows, specially to be compatible with charmcraft cache, the charmcraft.yaml files of all charms in this repository need to follow st124 notation.
Fixes #154
Please NOTE this PR targets a dev branch as there is still pending work:
* https://github.com/canonical/kubeflow-tensorboards-operator/issues/155
* https://github.com/canonical/kubeflow-tensorboards-operator/issues/157
1. Install charmcraft 3.x/edge
2. Build charms
3. They should successfully be built
=> build: refactor charmcraft.yaml to use st124 notation

charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_info.py
This repository contained a version of the istio_gateway_info lib that was not exactly the one that was published in Charmhub. This caused issues when trying to fetch new versions of the library.
This commit replaces the offending file with the library that is actually published.
Part of canonical/bundle-kubeflow#1209
=> fix: fetch istio_gateway_info lib with charmcraft to match published lib

charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_info.py
This repository contained a version of the istio_gateway_info lib that was not exactly the one that was published in Charmhub. This caused issues when trying to fetch new versions of the library.
This commit replaces the offending file with the library that is actually published.
Part of canonical/bundle-kubeflow#1209
=> fix: fetch istio_gateway_info lib with charmcraft to match published lib (#166)

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml
Upgrade using kf/manifests tag/v1.10.0-rc.1 (which corresponds to kf/kf 1.10.0-rc.0)
Regarding the TWA metrics, they will be enabled in a follow up PR similar to https://github.com/canonical/kubeflow-volumes-operator/pull/176, although we still need to discuss a bit more. 
Close https://warthogs.atlassian.net/browse/KF-6858
=> chore: upgrade to 1.10.0-rc.0

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml
Integrate 1.10.0-rc.1 rocks in preparation for a new release.
Fixes #172 
The only changes introduced in Kubeflow 1.10.0-rc.2 were image updates, thus we just need to integrate the rocks for version 1.10.0-rc.1 of the tensorboard components according to https://github.com/kubeflow/manifests/pull/3008.
=> chore: integrate 1.10.0-rc.1 rocks

.github/workflows/ci.yaml, .github/workflows/promote.yaml
Closes #175 
This PR updates all Ubuntu bases from `20.04` to `24.04`. Note that we also setup Python version `3.8`, which is what we currently use to pack the charms
=> chore: Update Ubuntu base in CI from 20.04 to 24.04

charms/tensorboard-controller/metadata.yaml, charms/tensorboards-web-app/metadata.yaml
Closes https://warthogs.atlassian.net/browse/KF-7145
The only changes introduced in Kubeflow 1.10.0-rc.3 were image updates, thus we just need to integrate the rocks for version 1.10.0 of the tensorboard components according to https://github.com/kubeflow/manifests/pull/3071.
Note that enabling the metrics will be handled in #173
=> chore: integrate tensorboards rocks 1.10.0

charms/tensorboard-controller/charmcraft.yaml, charms/tensorboard-controller/constraints.txt, charms/tensorboards-web-app/charmcraft.yaml, charms/tensorboards-web-app/constraints.txt
Due to python/importlib_metadata#516, we need to set up constaints
to the `setuptools-scm` to avoid install loops for these charms dependencies,
as recommended by the charmcraft team (see https://github.com/canonical/charmcraft/issues/2259#issuecomment-2842766428).
Fixes #184
=> fix(workaround): set constraints to setuptools-scm to avoid install loops

charms/tensorboard-controller/charmcraft.yaml, charms/tensorboard-controller/constraints.txt, charms/tensorboards-web-app/charmcraft.yaml, charms/tensorboards-web-app/constraints.txt
Due to python/importlib_metadata#516, we need to set up constaints to the `setuptools-scm` to avoid install loops for these charms dependencies, as recommended by the charmcraft team (see https://github.com/canonical/charmcraft/issues/2259#issuecomment-2842766428).
Fixes #184
=> cherry-pick(fix): set constraints to setuptools-scm to avoid install loops from #187

charms/tensorboard-controller/requirements-integration.txt, charms/tensorboard-controller/requirements-unit.txt, charms/tensorboard-controller/requirements.in, charms/tensorboard-controller/requirements.txt, charms/tensorboard-controller/src/charm.py, charms/tensorboard-controller/tests/integration/charms_dependencies.py, charms/tensorboard-controller/tests/integration/test_charm.py, charms/tensorboard-controller/tests/integration/utils.py, charms/tensorboards-web-app/requirements-integration.txt, charms/tensorboards-web-app/requirements-unit.txt, charms/tensorboards-web-app/requirements.in, charms/tensorboards-web-app/requirements.txt, charms/tensorboards-web-app/src/charm.py, charms/tensorboards-web-app/tests/integration/charms_dependencies.py, charms/tensorboards-web-app/tests/integration/test_charm.py
Move dependency charms deployed during tests to a separate file called
charms_dependencies.py. This enables programmatic access to them and
thus updating them centrally, probably with the use of `kfcicli`. This
uses the `CharmSpec` dataclass from chisme.
Ref canonical/bundle-kubeflow/issues/1256
=> refactor(tests): Move dependency charms to a separate file
